In [13]:
# import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
# Reading ratings file from github
ratings = pd.read_csv('C:/Users/User/Desktop/ANINDITADAS_SentimentRecommendedBasedProject/sample30.csv' , encoding ='latin-1')
ratings.head()  

id            brand  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1  AV14LG0R-jtxr-f38QfS         Lundberg   
2  AV14LG0R-jtxr-f38QfS         Lundberg   
3  AV16khLE-jtxr-f38VFn              K-Y   
4  AV16khLE-jtxr-f38VFn              K-Y   

                                          categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3  Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4  Personal Care,Medicine Cabinet,Lubricant/Sperm...   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
0                 NaN                 NaN               5   
1                True                 NaN               5   
2                True                 NaN               5   
3               False               False               1   
4               False               False               1   

                                        reviews_text reviews_title  \
0  i love this album. it's very good. more to the...  Just Awesome   
1  Good flavor. This review was collected as part...          Good   
2                                       Good flavor.          Good   
3  I read through the reviews on here before look...  Disappointed   
4  My husband bought this gel for us. The gel cau...    Irritation   

  reviews_userCity reviews_userProvince reviews_username user_sentiment  
0      Los Angeles                  NaN           joshua       Positive  
1              NaN                  NaN        dorothy w       Positive  
2              NaN                  NaN        dorothy w       Positive  
3              NaN                  NaN          rebecca       Negative  
4              NaN                  NaN        walker557       Negative

In [36]:
# Dividing the dataset into train and test
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.30, random_state=31)

ratings.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    30000 non-null  object
 1   brand                 30000 non-null  object
 2   categories            30000 non-null  object
 3   manufacturer          29859 non-null  object
 4   name                  30000 non-null  object
 5   reviews_date          29954 non-null  object
 6   reviews_didPurchase   15932 non-null  object
 7   reviews_doRecommend   27430 non-null  object
 8   reviews_rating        30000 non-null  int64 
 9   reviews_text          30000 non-null  object
 10  reviews_title         29810 non-null  object
 11  reviews_userCity      1929 non-null   object
 12  reviews_userProvince  170 non-null    object
 13  reviews_username      29937 non-null  object
 14  user_sentiment        29999 non-null  object
dtypes: int64(1), object(14)
memory usage

In [6]:
print(train.shape) 

(21000, 15)


In [7]:
print(test.shape)    

(9000, 15)


In [16]:
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.preprocessing import OneHotEncoder
from pandas.core.reshape.pivot import pivot

In [20]:

#pivot = df.piv# pivot the train eatings dataset into matrix format in which columns are categories and the rows are ids 
df_pivot = train.pivot_table(index='id', columns='categories', values= 'reviews_rating').fillna(0)
 
#cols = pivot.columns.to_flat_index().str.join('_')

df_pivot.head(4)  

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV13O1A8GV-KLJ3akUyj                                                0.0                                                         
AV14LG0R-jtxr-f38QfS                                                0.0                                                         
AV16khLE-jtxr-f38VFn                                                0.0                                                         
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV13O1A8GV-KLJ3akUyj                                                0.0                                                                   
AV14LG0R-jtxr-f38QfS                                                0.0                                                                   
AV16khLE-jtxr-f38VFn                                                0.0                                                                   
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV13O1A8GV-KLJ3akUyj                                                0.0                                                 
AV14LG0R-jtxr-f38QfS                                                0.0                                                 
AV16khLE-jtxr-f38VFn                                                0.0                                                 
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV13O1A8GV-KLJ3akUyj                                                0.0                                                       
AV14LG0R-jtxr-f38QfS                                                0.0                                                       
AV16khLE-jtxr-f38VFn                                                0.0                                                       
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                                                                                                                                                                  
AV13O1A8GV-KLJ3akUyj                                                0.0                                                                                                                                                                                             
AV14LG0R-jtxr-f38QfS                                                0.0                                              

In [21]:
# creating dummy train & dummy test datasets 

# copy the train dataset into dummy dummy_train
dummy_train = train.copy()

dummy_train.head() 

id          brand  \
11155  AVpf3VOfilAPnD_xjpun         Clorox   
22114  AVpf--o9LJeJML43G_Fq       Vaseline   
26218  AVpfPkrkilAPnD_xX-L9         Finish   
18966  AVpfJP1C1cnluZ0-e3Xy         Clorox   
29999  AVpfW8y_LJeJML437ySW  L'oreal Paris   

                                              categories       manufacturer  \
11155  Household Essentials,Cleaning Supplies,Kitchen...             Clorox   
22114  Personal Care,Skin Care,Hand Cream,Beauty,Body...           Vaseline   
26218  Household Essentials,Cleaning Supplies,Dish De...  Reckitt Benckiser   
18966  Household Chemicals,Household Cleaners,Bath & ...     AmazonUs/CLOO7   
29999  Beauty,Hair Care,Shampoo & Conditioner,Holiday...      L'oreal Paris   

                                                    name  \
11155  Clorox Disinfecting Wipes Value Pack Scented 1...   
22114  Vaseline Intensive Care Healthy Hands Stronger...   
26218  Finish Gelpacs Dishwasher Detergent, Orange Sc...   
18966               Clorox Disinfecting Bathroom Cleaner   
29999  L'or233al Paris Elvive Extraordinary Clay Reba...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
11155  2015-01-05T00:00:00.000Z               False                True   
22114  2016-03-19T00:00:00.000Z               False                True   
26218  2013-04-25T16:51:02.000Z                 NaN                True   
18966  2012-01-21T00:00:00.000Z               False                True   
29999  2017-01-19T00:00:00.000Z               False                True   

       reviews_rating                                       reviews_text  \
11155               5  It's quick and easy compared to using a spray ...   
22114               4  Stronger nails after a week of daily use. Not ...   
26218               5  REALLY DOES CLEAN EVERYTHING AND SO GOOD ON GL...   
18966               5  These wipes are great for cleaning in the kitc...   
29999               5  I received this product complimentary from inf...   

                  reviews_title reviews_userCity reviews_userProvince  \
11155              Clorox wipes              NaN                  NaN   
22114         VERY GOOD PRODUCT              NaN                  NaN   
26218                 Excellent              NaN                  NaN   
18966  Great wipes, great smell              NaN                  NaN   
29999  Conditioned into healthy              NaN                  NaN   

      reviews_username user_sentiment  
11155         gor05751       Positive  
22114          annavsl       Positive  
26218         bluenose       Positive  
18966             kiki       Positive  
29999        kcoopxoxo       Positive

In [23]:
# The categories not rated by user is marked as 1 for prediction
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1) 

In [35]:
# convert the dummy train dataset into matrix format
dummy_train = train.pivot_table(index='id', columns='categories', values= 'reviews_rating').fillna(1)     

In [63]:
dummy_train.head()      

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV13O1A8GV-KLJ3akUyj                                                1.0                                                         
AV14LG0R-jtxr-f38QfS                                                1.0                                                         
AV16khLE-jtxr-f38VFn                                                1.0                                                         
AV1YGDqsGV-KLJ3adc-O                                                1.0                                                         
AV1YIch7GV-KLJ3addeG                                                1.0                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV13O1A8GV-KLJ3akUyj                                                1.0                                                                   
AV14LG0R-jtxr-f38QfS                                                1.0                                                                   
AV16khLE-jtxr-f38VFn                                                1.0                                                                   
AV1YGDqsGV-KLJ3adc-O                                                1.0                                                                   
AV1YIch7GV-KLJ3addeG                                                1.0                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV13O1A8GV-KLJ3akUyj                                                1.0                                                 
AV14LG0R-jtxr-f38QfS                                                1.0                                                 
AV16khLE-jtxr-f38VFn                                                1.0                                                 
AV1YGDqsGV-KLJ3adc-O                                                1.0                                                 
AV1YIch7GV-KLJ3addeG                                                1.0                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV13O1A8GV-KLJ3akUyj                                                1.0                                                       
AV14LG0R-jtxr-f38QfS                                                1.0                                                       
AV16khLE-jtxr-f38VFn                                                1.0                                                       
AV1YGDqsGV-KLJ3adc-O                                                1.0                                                       
AV1YIch7GV-KLJ3addeG                                                1.0                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [37]:
# User similarity Matrix

# Using cosine similarity
df_pivot.index.nunique() 

252

In [38]:
from sklearn.metrics.pairwise import pairwise_distances 

In [40]:
# creating the user similarity Matrix using pairwise_distance function
user_correlation = 1 - pairwise_distances(df_pivot, metric= 'cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)  

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [41]:
user_correlation.shape 

(252, 252)

In [42]:
# using adjusted cosine
# prediction user-user
user_correlation[user_correlation<0]=0
user_correlation 

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
# this is dot product between correlated matrix and user-item matrix 
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
user_predicted_ratings.shape 

(252, 252)

In [45]:
user_predicted_ratings 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head() 

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV13O1A8GV-KLJ3akUyj                                                0.0                                                         
AV14LG0R-jtxr-f38QfS                                                0.0                                                         
AV16khLE-jtxr-f38VFn                                                0.0                                                         
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                         
AV1YIch7GV-KLJ3addeG                                                0.0                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV13O1A8GV-KLJ3akUyj                                                0.0                                                                   
AV14LG0R-jtxr-f38QfS                                                0.0                                                                   
AV16khLE-jtxr-f38VFn                                                0.0                                                                   
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                                   
AV1YIch7GV-KLJ3addeG                                                0.0                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV13O1A8GV-KLJ3akUyj                                                0.0                                                 
AV14LG0R-jtxr-f38QfS                                                0.0                                                 
AV16khLE-jtxr-f38VFn                                                0.0                                                 
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                 
AV1YIch7GV-KLJ3addeG                                                0.0                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV13O1A8GV-KLJ3akUyj                                                0.0                                                       
AV14LG0R-jtxr-f38QfS                                                0.0                                                       
AV16khLE-jtxr-f38VFn                                                0.0                                                       
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                       
AV1YIch7GV-KLJ3addeG                                                0.0                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [60]:
# Finding the top 5 recommendation for the user
# take the user id as input

user_input = str(input("Enter your user name"))
print(user_input) 

Enter your user nameAV13O1A8GV-KLJ3akUyj
AV13O1A8GV-KLJ3akUyj


In [61]:
user_final_rating.head(20) 

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV13O1A8GV-KLJ3akUyj                                                0.0                                                         
AV14LG0R-jtxr-f38QfS                                                0.0                                                         
AV16khLE-jtxr-f38VFn                                                0.0                                                         
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                         
AV1YIch7GV-KLJ3addeG                                                0.0                                                         
AV1YlENIglJLPUi8IHsX                                                0.0                                                         
AV1YmBrdGV-KLJ3adewb                                                0.0                                                         
AV1YmDL9vKc47QAVgr7_                                                0.0                                                         
AV1Ymf_rglJLPUi8II2v                                                0.0                                                         
AV1Yn94nvKc47QAVgtst                                                0.0                                                         
AV1YnUMYglJLPUi8IJpK                                                0.0                                                         
AV1Ynb3bglJLPUi8IJxJ                                                0.0                                                         
AV1YneDPglJLPUi8IJyQ                                                0.0                                                         
AV1YpiJvvKc47QAVguxy                                                0.0                                                         
AV1YqAaMGV-KLJ3adiDj                                                0.0                                                         
AV1Ys0kTvKc47QAVgx1C                                                0.0                                                         
AV1YtGjdglJLPUi8IOfJ                                                0.0                                                         
AV1ZSp2uglJLPUi8IQFy                                                0.0                                                         
AV1ZT7GLglJLPUi8IQLI                                                0.0                                                         
AV1ZVIgy-jtxr-f31W9N                                                0.0                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV13O1A8GV-KLJ3akUyj                                                0.0                                                                   
AV14LG0R-jtxr-f38QfS                                                0.0                                                                   
AV16khLE-jtxr-f38VFn                                                0.0                                                                   
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                                   
AV1YIch7GV-KLJ3addeG                                                0.0                                                                   
AV1YlENIglJLPUi8IHsX                                                0.0                                                                   
AV1YmBrdGV-KLJ3adewb                             

In [62]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
# = user_final_rating.sort_values(by=user_input, ascending=False)
d 

categories
Movies, Music & Books,Music,R&b,Movies & TV,Movie Bundles & Collections,CDs & Vinyl,Rap & Hip-Hop,Bass,Music on CD or Vinyl,Rap,Hip-Hop,Mainstream Rap,Pop Rap                                                                          25.0
Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories                                                                                                                                  0.0
Personal Care,Bath, Shower & Soap,Bar Soap,Bath & Body,Bath Accessories,Soap,Beauty & Personal Care,Skin Care,Body,Cleansers,Soaps,Beauty,Wholesale Lots                                                                                 0.0
Movies, Music & Books,Movies,Sci-Fi & Fantasy,Romance,Movies & TV,Blu-ray,Documentary,Drama,Movies & Music,Movies & TV Shows                                                                                                             0.0
Movies, Music & Books,Music,Gospel & Chri

In [67]:
# Mapping with the categories Title / Genres
categories_mapping = pd.read_csv('C:/Users/User/Desktop/ANINDITADAS_SentimentRecommendedBasedProject/sample30.csv')
categories_mapping.head()

id            brand  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1  AV14LG0R-jtxr-f38QfS         Lundberg   
2  AV14LG0R-jtxr-f38QfS         Lundberg   
3  AV16khLE-jtxr-f38VFn              K-Y   
4  AV16khLE-jtxr-f38VFn              K-Y   

                                          categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3  Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4  Personal Care,Medicine Cabinet,Lubricant/Sperm...   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
0                 NaN                 NaN               5   
1                True                 NaN               5   
2                True                 NaN               5   
3               False               False               1   
4               False               False               1   

                                        reviews_text reviews_title  \
0  i love this album. it's very good. more to the...  Just Awesome   
1  Good flavor. This review was collected as part...          Good   
2                                       Good flavor.          Good   
3  I read through the reviews on here before look...  Disappointed   
4  My husband bought this gel for us. The gel cau...    Irritation   

  reviews_userCity reviews_userProvince reviews_username user_sentiment  
0      Los Angeles                  NaN           joshua       Positive  
1              NaN                  NaN        dorothy w       Positive  
2              NaN                  NaN        dorothy w       Positive  
3              NaN                  NaN          rebecca       Negative  
4              NaN                  NaN        walker557       Negative

In [69]:
d = pd.merge(d,categories_mapping,left_on='categories',right_on='categories', how = 'left')
d.head() 

categories  AV13O1A8GV-KLJ3akUyj  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...                  25.0   
1  Auto & Tires,Automotive Interior,Car Organizer...                   0.0   
2  Auto & Tires,Automotive Interior,Car Organizer...                   0.0   
3  Auto & Tires,Automotive Interior,Car Organizer...                   0.0   
4  Auto & Tires,Automotive Interior,Car Organizer...                   0.0   

                     id            brand                        manufacturer  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music  Universal Music Group / Cash Money   
1  AVpf5CnILJeJML43FjaU     Weather Tech                         WeatherTech   
2  AVpf5CnILJeJML43FjaU     Weather Tech                         WeatherTech   
3  AVpf5CnILJeJML43FjaU     Weather Tech                         WeatherTech   
4  AVpf5CnILJeJML43FjaU     Weather Tech                         WeatherTech   

                                                name  \
0          Pink Friday: Roman Reloaded Re-Up (w/dvd)   
1  WeatherTech 40647 14-15 Outlander Cargo Liners...   
2  WeatherTech 40647 14-15 Outlander Cargo Liners...   
3  WeatherTech 40647 14-15 Outlander Cargo Liners...   
4  WeatherTech 40647 14-15 Outlander Cargo Liners...   

               reviews_date reviews_didPurchase reviews_doRecommend  \
0  2012-11-30T06:21:45.000Z                 NaN                 NaN   
1      2014-01-03T03:00:00Z                 NaN                 NaN   
2      2015-05-02T09:34:00Z                 NaN                 NaN   
3      2015-11-06T05:19:00Z                 NaN                 NaN   
4      2015-08-02T11:03:00Z                 NaN                 NaN   

   reviews_rating                                       reviews_text  \
0               5  i love this album. it's very good. more to the...   
1               4  Great selection and easy checkout! The only th...   
2               4  Wish there were better product description. In...   
3               5                              Fast shipping Thanks.   
4               5                          Cheap price good quality.   

  reviews_title reviews_userCity reviews_userProvince reviews_username  \
0  Just Awesome      Los Angeles                  NaN           joshua   
1           NaN              NaN                  NaN           sweeny   
2           NaN              NaN                  NaN   michael norman   
3           NaN              NaN                  NaN   manuel miranda   
4           NaN              NaN                  NaN            brent   

  user_sentiment  
0       Positive  
1       Positive  
2       Positive  
3       Positive  
4       Positive

In [75]:
# Evalution user-user 
# find out the common user from test and dataset 
common = test[test.id.isin(train.id)]
common.shape  

(8978, 15)

In [76]:
common.head() 

id          brand  \
4332   AVpe9W4D1cnluZ0-avf0         Hoover   
3434   AVpe5s3RLJeJML43x4eA        Pantene   
20634  AVpfkak01cnluZ0-nJj6      Starbucks   
26479  AVpfPPkEilAPnD_xX3cP         Aveeno   
29726  AVpfW8y_LJeJML437ySW  L'oreal Paris   

                                              categories  \
4332   Home,Home Appliances,Vacuums & Floor Care,Upri...   
3434   Personal Care,Hair Care,Conditioner,Beauty,Sha...   
20634  Food & Beverage,Coffee, Tea & Cocoa,Coffee,Foo...   
26479  Personal Care,Sun Care,Featured Brands,Health ...   
29726  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   

                      manufacturer  \
4332                        Hoover   
3434       Pantene Pro-V Hair Care   
20634  American Coffee Partnership   
26479                  Aveeno Baby   
29726                L'oreal Paris   

                                                    name  \
4332   Hoover174 Platinum Collection153 Lightweight B...   
3434   Pantene Pro-V Expert Collection Age Defy Condi...   
20634  Starbucks Iced Expresso Classics Vanilla Latte...   
26479  Aveeno Baby Continuous Protection Lotion Sunsc...   
29726  L'or233al Paris Elvive Extraordinary Clay Reba...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
4332   2010-09-10T00:00:00.000Z               False                True   
3434   2016-04-08T00:00:00.000Z               False                 NaN   
20634  2016-04-21T00:00:00.000Z               False                True   
26479      2013-07-05T00:00:00Z                 NaN                 NaN   
29726  2016-12-15T00:00:00.000Z               False                True   

       reviews_rating                                       reviews_text  \
4332                5  I've only owned this product for 4 weeks so co...   
3434                5  This is thick stuff! I was surprised by the co...   
20634               5                                           Love it!   
26479               1  My 6 year old daughter has sensitive skin, and...   
29726               5  I thought this was fantastic! My hair felt sup...   

                                        reviews_title reviews_userCity  \
4332                                        Great buy              NaN   
3434                            Serious conditioning!              NaN   
20634  Love the taste! Would have highly recommended!              NaN   
26479                            Not sensitive enough              NaN   
29726                                       Loved it!              NaN   

      reviews_userProvince reviews_username user_sentiment  
4332                   NaN         sansname       Positive  
3434                   NaN     jennypstrong       Positive  
20634                  NaN           girlie       Positive  
26479                  NaN       kasheville       Positive  
29726                  NaN             payy       Positive

In [80]:
 common.head() 

id          brand  \
4332   AVpe9W4D1cnluZ0-avf0         Hoover   
3434   AVpe5s3RLJeJML43x4eA        Pantene   
20634  AVpfkak01cnluZ0-nJj6      Starbucks   
26479  AVpfPPkEilAPnD_xX3cP         Aveeno   
29726  AVpfW8y_LJeJML437ySW  L'oreal Paris   

                                              categories  \
4332   Home,Home Appliances,Vacuums & Floor Care,Upri...   
3434   Personal Care,Hair Care,Conditioner,Beauty,Sha...   
20634  Food & Beverage,Coffee, Tea & Cocoa,Coffee,Foo...   
26479  Personal Care,Sun Care,Featured Brands,Health ...   
29726  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   

                      manufacturer  \
4332                        Hoover   
3434       Pantene Pro-V Hair Care   
20634  American Coffee Partnership   
26479                  Aveeno Baby   
29726                L'oreal Paris   

                                                    name  \
4332   Hoover174 Platinum Collection153 Lightweight B...   
3434   Pantene Pro-V Expert Collection Age Defy Condi...   
20634  Starbucks Iced Expresso Classics Vanilla Latte...   
26479  Aveeno Baby Continuous Protection Lotion Sunsc...   
29726  L'or233al Paris Elvive Extraordinary Clay Reba...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
4332   2010-09-10T00:00:00.000Z               False                True   
3434   2016-04-08T00:00:00.000Z               False                 NaN   
20634  2016-04-21T00:00:00.000Z               False                True   
26479      2013-07-05T00:00:00Z                 NaN                 NaN   
29726  2016-12-15T00:00:00.000Z               False                True   

       reviews_rating                                       reviews_text  \
4332                5  I've only owned this product for 4 weeks so co...   
3434                5  This is thick stuff! I was surprised by the co...   
20634               5                                           Love it!   
26479               1  My 6 year old daughter has sensitive skin, and...   
29726               5  I thought this was fantastic! My hair felt sup...   

                                        reviews_title reviews_userCity  \
4332                                        Great buy              NaN   
3434                            Serious conditioning!              NaN   
20634  Love the taste! Would have highly recommended!              NaN   
26479                            Not sensitive enough              NaN   
29726                                       Loved it!              NaN   

      reviews_userProvince reviews_username user_sentiment  
4332                   NaN         sansname       Positive  
3434                   NaN     jennypstrong       Positive  
20634                  NaN           girlie       Positive  
26479                  NaN       kasheville       Positive  
29726                  NaN             payy       Positive

In [81]:
#convert into user categories matrix
common_user_based_matrix = common.pivot_table(index='id', columns='categories', values= 'reviews_rating')
common_user_based_matrix.head() 

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV16khLE-jtxr-f38VFn                                                NaN                                                         
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                         
AV1YlENIglJLPUi8IHsX                                                NaN                                                         
AV1YmBrdGV-KLJ3adewb                                                NaN                                                         
AV1YmDL9vKc47QAVgr7_                                                NaN                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV16khLE-jtxr-f38VFn                                                NaN                                                                   
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                                   
AV1YlENIglJLPUi8IHsX                                                NaN                                                                   
AV1YmBrdGV-KLJ3adewb                                                NaN                                                                   
AV1YmDL9vKc47QAVgr7_                                                NaN                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV16khLE-jtxr-f38VFn                                                NaN                                                 
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                 
AV1YlENIglJLPUi8IHsX                                                NaN                                                 
AV1YmBrdGV-KLJ3adewb                                                NaN                                                 
AV1YmDL9vKc47QAVgr7_                                                NaN                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV16khLE-jtxr-f38VFn                                                NaN                                                       
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                       
AV1YlENIglJLPUi8IHsX                                                NaN                                                       
AV1YmBrdGV-KLJ3adewb                                                NaN                                                       
AV1YmDL9vKc47QAVgr7_                                                NaN                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [77]:
dummy_test = common.copy()
dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)
dummy_test = dummy_test.pivot_table(index='id', columns='categories', values= 'reviews_rating').fillna(0) 

In [78]:
dummy_test.shape 

(199, 199)

In [83]:
common_user_based_matrix.head()  

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV16khLE-jtxr-f38VFn                                                NaN                                                         
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                         
AV1YlENIglJLPUi8IHsX                                                NaN                                                         
AV1YmBrdGV-KLJ3adewb                                                NaN                                                         
AV1YmDL9vKc47QAVgr7_                                                NaN                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV16khLE-jtxr-f38VFn                                                NaN                                                                   
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                                   
AV1YlENIglJLPUi8IHsX                                                NaN                                                                   
AV1YmBrdGV-KLJ3adewb                                                NaN                                                                   
AV1YmDL9vKc47QAVgr7_                                                NaN                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV16khLE-jtxr-f38VFn                                                NaN                                                 
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                 
AV1YlENIglJLPUi8IHsX                                                NaN                                                 
AV1YmBrdGV-KLJ3adewb                                                NaN                                                 
AV1YmDL9vKc47QAVgr7_                                                NaN                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV16khLE-jtxr-f38VFn                                                NaN                                                       
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                       
AV1YlENIglJLPUi8IHsX                                                NaN                                                       
AV1YmBrdGV-KLJ3adewb                                                NaN                                                       
AV1YmDL9vKc47QAVgr7_                                                NaN                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [84]:
# convert the user correlation matrix into dataframe
user_correlation_df = pd.DataFrame(user_correlation)
user_correlation_df.head() 

0    1    2    3    4    5    6    7    8    9    ...  242  243  244  245  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   246  247  248  249  250  251  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 252 columns]

In [92]:
# df_subtracted.head()
user_correlation_df['id'] = df_substracted.index

user_correlation_df.set_index('id',inplace=True)
user_correlation_df.head() 

0    1    2    3    4    \
id                                                                            
Auto & Tires,Automotive Interior,Car Organizers...  1.0  0.0  0.0  0.0  0.0   
Auto & Tires,Automotive Interior,Car Organizers...  0.0  1.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  0.0  1.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  0.0  0.0  1.0  0.0   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...  0.0  0.0  0.0  0.0  1.0   

                                                    5    6    7    8    9    \
id                                                                            
Auto & Tires,Automotive Interior,Car Organizers...  0.0  0.0  0.0  0.0  0.0   
Auto & Tires,Automotive Interior,Car Organizers...  0.0  0.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  0.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  0.0  0.0  0.0  0.0   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...  0.0  0.0  0.0  0.0  0.0   

                                                    ...  242  243  244  245  \
id                                                  ...                       
Auto & Tires,Automotive Interior,Car Organizers...  ...  0.0  0.0  0.0  0.0   
Auto & Tires,Automotive Interior,Car Organizers...  ...  0.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  ...  0.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  ...  0.0  0.0  0.0  0.0   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...  ...  0.0  0.0  0.0  0.0   

                                                    246  247  248  249  250  \
id                                                                            
Auto & Tires,Automotive Interior,Car Organizers...  0.0  0.0  0.0  0.0  0.0   
Auto & Tires,Automotive Interior,Car Organizers...  0.0  0.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  0.0  0.0  0.0  0.0   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  0.0  0.0  0.0  0.0   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...  0.0  0.0  0.0  0.0  0.0   

                                                    251  
id                                                       
Auto & Tires,Automotive Interior,Car Organizers...  0.0  
Auto & Tires,Automotive Interior,Car Organizers...  0.0  
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...  0.0  
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...  0.0  

[5 rows x 252 columns]

In [86]:
common.head(5) 

id          brand  \
4332   AVpe9W4D1cnluZ0-avf0         Hoover   
3434   AVpe5s3RLJeJML43x4eA        Pantene   
20634  AVpfkak01cnluZ0-nJj6      Starbucks   
26479  AVpfPPkEilAPnD_xX3cP         Aveeno   
29726  AVpfW8y_LJeJML437ySW  L'oreal Paris   

                                              categories  \
4332   Home,Home Appliances,Vacuums & Floor Care,Upri...   
3434   Personal Care,Hair Care,Conditioner,Beauty,Sha...   
20634  Food & Beverage,Coffee, Tea & Cocoa,Coffee,Foo...   
26479  Personal Care,Sun Care,Featured Brands,Health ...   
29726  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   

                      manufacturer  \
4332                        Hoover   
3434       Pantene Pro-V Hair Care   
20634  American Coffee Partnership   
26479                  Aveeno Baby   
29726                L'oreal Paris   

                                                    name  \
4332   Hoover174 Platinum Collection153 Lightweight B...   
3434   Pantene Pro-V Expert Collection Age Defy Condi...   
20634  Starbucks Iced Expresso Classics Vanilla Latte...   
26479  Aveeno Baby Continuous Protection Lotion Sunsc...   
29726  L'or233al Paris Elvive Extraordinary Clay Reba...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
4332   2010-09-10T00:00:00.000Z               False                True   
3434   2016-04-08T00:00:00.000Z               False                 NaN   
20634  2016-04-21T00:00:00.000Z               False                True   
26479      2013-07-05T00:00:00Z                 NaN                 NaN   
29726  2016-12-15T00:00:00.000Z               False                True   

       reviews_rating                                       reviews_text  \
4332                5  I've only owned this product for 4 weeks so co...   
3434                5  This is thick stuff! I was surprised by the co...   
20634               5                                           Love it!   
26479               1  My 6 year old daughter has sensitive skin, and...   
29726               5  I thought this was fantastic! My hair felt sup...   

                                        reviews_title reviews_userCity  \
4332                                        Great buy              NaN   
3434                            Serious conditioning!              NaN   
20634  Love the taste! Would have highly recommended!              NaN   
26479                            Not sensitive enough              NaN   
29726                                       Loved it!              NaN   

      reviews_userProvince reviews_username user_sentiment  
4332                   NaN         sansname       Positive  
3434                   NaN     jennypstrong       Positive  
20634                  NaN           girlie       Positive  
26479                  NaN       kasheville       Positive  
29726                  NaN             payy       Positive

In [94]:
list_name = common.id.tolist()
user_correlation_df.columns = df_substracted.index.tolist()

user_correlation_df_1 = user_correlation_df[user_correlation_df.index.isin(list_name)]  

In [95]:
user_correlation_df_1.shape 

(0, 252)

In [99]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)] 

In [100]:
user_correlation_df_3 = user_correlation_df_2.T 

In [105]:
user_correlation_df_3.head()     

Empty DataFrame
Columns: []
Index: []

In [106]:
user_correlation_df_3.shape 

(0, 0)

In [110]:
user_correlation_df_3[user_correlation_df_3<0]=0

In [112]:
#as shape is (0,0) --> it will not work
common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings 

ValueError: shapes (0,0) and (199,199) not aligned: 0 (dim 1) != 199 (dim 0)

In [113]:
dummy_test = common.copy()
dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)
dummy_test = dummy_test.pivot_table(index='id', columns='categories', values= 'reviews_rating').fillna(0) 

In [114]:
dummy_test.shape 

(199, 199)

In [115]:
common_user_based_matrix.head() 

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV16khLE-jtxr-f38VFn                                                NaN                                                         
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                         
AV1YlENIglJLPUi8IHsX                                                NaN                                                         
AV1YmBrdGV-KLJ3adewb                                                NaN                                                         
AV1YmDL9vKc47QAVgr7_                                                NaN                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV16khLE-jtxr-f38VFn                                                NaN                                                                   
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                                   
AV1YlENIglJLPUi8IHsX                                                NaN                                                                   
AV1YmBrdGV-KLJ3adewb                                                NaN                                                                   
AV1YmDL9vKc47QAVgr7_                                                NaN                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV16khLE-jtxr-f38VFn                                                NaN                                                 
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                 
AV1YlENIglJLPUi8IHsX                                                NaN                                                 
AV1YmBrdGV-KLJ3adewb                                                NaN                                                 
AV1YmDL9vKc47QAVgr7_                                                NaN                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV16khLE-jtxr-f38VFn                                                NaN                                                       
AV1YGDqsGV-KLJ3adc-O                                                NaN                                                       
AV1YlENIglJLPUi8IHsX                                                NaN                                                       
AV1YmBrdGV-KLJ3adewb                                                NaN                                                       
AV1YmDL9vKc47QAVgr7_                                                NaN                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [116]:
dummy_test.head() 

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV16khLE-jtxr-f38VFn                                                0.0                                                         
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                         
AV1YlENIglJLPUi8IHsX                                                0.0                                                         
AV1YmBrdGV-KLJ3adewb                                                0.0                                                         
AV1YmDL9vKc47QAVgr7_                                                0.0                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV16khLE-jtxr-f38VFn                                                0.0                                                                   
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                                   
AV1YlENIglJLPUi8IHsX                                                0.0                                                                   
AV1YmBrdGV-KLJ3adewb                                                0.0                                                                   
AV1YmDL9vKc47QAVgr7_                                                0.0                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV16khLE-jtxr-f38VFn                                                0.0                                                 
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                 
AV1YlENIglJLPUi8IHsX                                                0.0                                                 
AV1YmBrdGV-KLJ3adewb                                                0.0                                                 
AV1YmDL9vKc47QAVgr7_                                                0.0                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV16khLE-jtxr-f38VFn                                                0.0                                                       
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                       
AV1YlENIglJLPUi8IHsX                                                0.0                                                       
AV1YmBrdGV-KLJ3adewb                                                0.0                                                       
AV1YmDL9vKc47QAVgr7_                                                0.0                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [125]:
common_user_based_matrix = np.multiply(common_user_based_matrix,dummy_test)   

In [126]:
user_predicted_ratings.head()  

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [128]:
from sklearn .preprocessing import MinMaxScaler
from numpy import *
x = common_user_based_matrix.copy()
x = x[x>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(x))
y = (scaler.transform(x))

print(y) 

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [129]:
common_ = common.pivot_table(index='id', columns='categories', values= 'reviews_rating') 

In [130]:
# finding total non -Nan value
total_non_nan = np.count_nonzero(~np.isnan(y))  

In [131]:
rmse = (sum(sum((common_ - y)**2))/total_non_nan)**0.5
print(rmse)        

3.483132926898711


In [133]:
# Item, based similarity

df_pivot = train.pivot_table(index='id', columns='categories', values= 'reviews_rating').T
df_pivot.head()  

id                                                  AV13O1A8GV-KLJ3akUyj  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV14LG0R-jtxr-f38QfS  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV16khLE-jtxr-f38VFn  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YGDqsGV-KLJ3adc-O  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YIch7GV-KLJ3addeG  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YlENIglJLPUi8IHsX  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YmBrdGV-KLJ3adewb  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YmDL9vKc47QAVgr7_  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Orga

In [136]:
# Normalising the categories rating for each movie for using the adjusted cosine

mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T 

df_subtracted.head()  

id                                                  AV13O1A8GV-KLJ3akUyj  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV14LG0R-jtxr-f38QfS  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV16khLE-jtxr-f38VFn  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YGDqsGV-KLJ3adc-O  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YIch7GV-KLJ3addeG  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YlENIglJLPUi8IHsX  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YmBrdGV-KLJ3adewb  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Auto & Tires,Motorcycle and ATV,Motorcycle,Moto...                   NaN   
Baby,Nursery & Decor,Furniture,Rocking Chairs,G...                   NaN   

id                                                  AV1YmDL9vKc47QAVgr7_  \
categories                                                                 
Auto & Tires,Automotive Interior,Car Organizers...                   NaN   
Auto & Tires,Automotive Interior,Car Orga

In [135]:
from sklearn.metrics.pairwise import pairwise_distances  

In [138]:
# item similarity matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric = 'cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation) 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [139]:
item_correlation.shape 

(252, 252)

In [140]:
item_correlation[item_correlation<0]=0
item_correlation 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [141]:
# PREDICTION ITEM-ITEM
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [142]:
item_predicted_ratings.shape 

(252, 252)

In [143]:
dummy_train.shape 

(252, 252)

In [144]:
# Filter the rating only for categories not rated by the user recommendation
item_final_ratings = np.multiply(item_predicted_ratings,dummy_train)
item_final_ratings.head() 

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories  \
id                                                                                                                              
AV13O1A8GV-KLJ3akUyj                                                0.0                                                         
AV14LG0R-jtxr-f38QfS                                                0.0                                                         
AV16khLE-jtxr-f38VFn                                                0.0                                                         
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                         
AV1YIch7GV-KLJ3addeG                                                0.0                                                         

categories            Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Tool Chests,Tool Boxes - Truck Bed,Tools  \
id                                                                                                                                        
AV13O1A8GV-KLJ3akUyj                                                0.0                                                                   
AV14LG0R-jtxr-f38QfS                                                0.0                                                                   
AV16khLE-jtxr-f38VFn                                                0.0                                                                   
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                                   
AV1YIch7GV-KLJ3addeG                                                0.0                                                                   

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tire Tubes  \
id                                                                                                                      
AV13O1A8GV-KLJ3akUyj                                                0.0                                                 
AV14LG0R-jtxr-f38QfS                                                0.0                                                 
AV16khLE-jtxr-f38VFn                                                0.0                                                 
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                 
AV1YIch7GV-KLJ3addeG                                                0.0                                                 

categories            Auto & Tires,Motorcycle and ATV,Motorcycle,Motorcycle Parts,Motorcycle Tires,Cruiser,Tires,Tire Tubes  \
id                                                                                                                            
AV13O1A8GV-KLJ3akUyj                                                0.0                                                       
AV14LG0R-jtxr-f38QfS                                                0.0                                                       
AV16khLE-jtxr-f38VFn                                                0.0                                                       
AV1YGDqsGV-KLJ3adc-O                                                0.0                                                       
AV1YIch7GV-KLJ3addeG                                                0.0                                                       

categories            Baby,Nursery & Decor,Furniture,Rocking Chairs,Gliders & Rockers,Baby Gear,Nursery Furniture,Gliders,Stork Craft,Rockers, Gliders,Kitchen & Dining Features,Living Room Furniture,Living Room Chairs,Home & Kitchen Features,Nursery Seating  \
id                                                                                                                         

In [145]:
# Find the TOP 5 recommendation for users
# take the id as input 

user_input = str(input("Enter your user id"))
print(user_input)  

Enter your user idAV1YGDqsGV-KLJ3adc-O
AV1YGDqsGV-KLJ3adc-O


In [146]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
# = user_final_rating.sort_values(by=user_input, ascending=False)
d 

categories
Household Essentials,Cleaning Supplies,Glass Cleaners,Health & Household,Household Supplies,Household Cleaning,Featured Brands,Home And Storage & Org,Thanksgathering,All-purpose Cleaners,Target Restock,Food & Grocery,Glass & Window    16.775851
Auto & Tires,Automotive Interior,Car Organizers,Interior Car Accessories,Cargo Mat,Interior Accessories                                                                                                                                     0.000000
Personal Care,Bath, Shower & Soap,Bar Soap,Bath & Body,Bath Accessories,Soap,Beauty & Personal Care,Skin Care,Body,Cleansers,Soaps,Beauty,Wholesale Lots                                                                                    0.000000
Movies, Music & Books,Movies,Sci-Fi & Fantasy,Romance,Movies & TV,Blu-ray,Documentary,Drama,Movies & Music,Movies & TV Shows                                                                                                                0.000000
Movies, M

In [147]:
# Mapping with the categories Title / Genres
categories_mapping = pd.read_csv('C:/Users/User/Desktop/ANINDITADAS_SentimentRecommendedBasedProject/sample30.csv')
categories_mapping.head() 

id            brand  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1  AV14LG0R-jtxr-f38QfS         Lundberg   
2  AV14LG0R-jtxr-f38QfS         Lundberg   
3  AV16khLE-jtxr-f38VFn              K-Y   
4  AV16khLE-jtxr-f38VFn              K-Y   

                                          categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3  Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4  Personal Care,Medicine Cabinet,Lubricant/Sperm...   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
0                 NaN                 NaN               5   
1                True                 NaN               5   
2                True                 NaN               5   
3               False               False               1   
4               False               False               1   

                                        reviews_text reviews_title  \
0  i love this album. it's very good. more to the...  Just Awesome   
1  Good flavor. This review was collected as part...          Good   
2                                       Good flavor.          Good   
3  I read through the reviews on here before look...  Disappointed   
4  My husband bought this gel for us. The gel cau...    Irritation   

  reviews_userCity reviews_userProvince reviews_username user_sentiment  
0      Los Angeles                  NaN           joshua       Positive  
1              NaN                  NaN        dorothy w       Positive  
2              NaN                  NaN        dorothy w       Positive  
3              NaN                  NaN          rebecca       Negative  
4              NaN                  NaN        walker557       Negative

In [148]:
d = pd.merge(d,categories_mapping,left_on='categories',right_on='categories', how = 'left')
d.head() 

categories  AV1YGDqsGV-KLJ3adc-O  \
0  Household Essentials,Cleaning Supplies,Glass C...             16.775851   
1  Household Essentials,Cleaning Supplies,Glass C...             16.775851   
2  Household Essentials,Cleaning Supplies,Glass C...             16.775851   
3  Household Essentials,Cleaning Supplies,Glass C...             16.775851   
4  Household Essentials,Cleaning Supplies,Glass C...             16.775851   

                     id   brand manufacturer  \
0  AV1YGDqsGV-KLJ3adc-O  Windex       Windex   
1  AV1YGDqsGV-KLJ3adc-O  Windex       Windex   
2  AV1YGDqsGV-KLJ3adc-O  Windex       Windex   
3  AV1YGDqsGV-KLJ3adc-O  Windex       Windex   
4  AV1YGDqsGV-KLJ3adc-O  Windex       Windex   

                                                name  \
0  Windex Original Glass Cleaner Refill 67.6oz (2...   
1  Windex Original Glass Cleaner Refill 67.6oz (2...   
2  Windex Original Glass Cleaner Refill 67.6oz (2...   
3  Windex Original Glass Cleaner Refill 67.6oz (2...   
4  Windex Original Glass Cleaner Refill 67.6oz (2...   

               reviews_date reviews_didPurchase reviews_doRecommend  \
0  2013-11-16T00:00:00.000Z               False               False   
1  2015-09-12T00:00:00.000Z               False               False   
2  2014-05-13T00:00:00.000Z               False               False   
3  2014-01-09T00:00:00.000Z               False               False   
4  2015-06-19T00:00:00.000Z               False               False   

   reviews_rating                                       reviews_text  \
0               1  Leaves windows with streaks, although it does ...   
1               1  it leaves streaks bad . i used windsheild wash...   
2               1  Very disappointed in this product. It leaves a...   
3               1  Windex used to be good years ago. Since they r...   
4               1  Having used Windex for years , I noticed in th...   

                                reviews_title reviews_userCity  \
0                       Doesn't clean windows              NaN   
1                      not what it used to be              NaN   
2                             Streaky windows              NaN   
3  The New Windex Formula Leaves a Nasty Film              NaN   
4                           Very Disappointed              NaN   

  reviews_userProvince reviews_username user_sentiment  
0                  NaN      mountainman       Positive  
1                  NaN             rick       Positive  
2                  NaN           paul67       Positive  
3                  NaN       regularguy       Negative  
4                  NaN         roteflea       Positive

In [151]:
train_new = pd.merge(train,categories_mapping,left_on='categories',right_on='categories',how = 'left')
train_new[train_new.id == 1].head() 

MemoryError: Unable to allocate 7.01 GiB for an array with shape (14, 67182182) and data type object